# Generated by Django 3.2.2 on 2022-02-07 10:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('cluster', models.CharField(blank=True, max_length=100, null=True)),
                ('cooccurence', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Kategorie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ort',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bezeichnung', models.CharField(max_length=100)),
                ('bemerkung', models.CharField(blank=True, max_length=200, null=True)),
                ('koordinate_b', models.CharField(blank=True, max_length=50, null=True)),
                ('koordinate_l', models.CharField(blank=True, max_length=50, null=True)),
                ('interview', models.CharField(max_length=100)),
                ('idee', models.ManyToManyField(to='youbeon_api.Idee')),
                ('kategorie', models.ManyToManyField(to='youbeon_api.Kategorie')),
                ('religion', models.ManyToManyField(to='youbeon_api.Religion')),
            ],
        ),
        migrations.CreateModel(
            name='Influencer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('bemerkung', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('trueReligion', models.BooleanField()),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('mentions', models.IntegerField(blank=True, null=True)),
                ('interview', models.CharField(max_length=100)),
                ('idee', models.ManyToManyField(to='youbeon_api.Idee')),
                ('kategorie', models.ManyToManyField(to='youbeon_api.Kategorie')),
                ('religion', models.ManyToManyField(to='youbeon_api.Religion')),
            ],
        ),
    ]
