# Generated by Django 2.1.1 on 2021-05-10 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Influencer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('bemerkung', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('osm_id', models.IntegerField()),
                ('gnd', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Kategorie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ort',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bezeichnung', models.CharField(max_length=100)),
                ('bemerkung', models.CharField(max_length=200)),
                ('koordinate_b', models.CharField(max_length=50)),
                ('koordinate_l', models.CharField(max_length=50)),
                ('osm_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
